[programs.localnet]
solana_twitter = "8NMfKrcjkHAJpacYTLbL6gPb9TFbta5JwbhLHDGay9cY"

[programs.devnet]
solana_twitter = "8NMfKrcjkHAJpacYTLbL6gPb9TFbta5JwbhLHDGay9cY"

[programs.mainnet]
solana_twitter = "8NMfKrcjkHAJpacYTLbL6gPb9TFbta5JwbhLHDGay9cY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/kitan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"

[workspace]
types = "apps/src/idl/"
